# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c842b71b36d6a658bc3df35d1d4bf438e60879ccc0d9264235ba1062b613995979f04e8789786e0cb69b3ec4d3b8b8e76997a3e3553da9c4c1ef41558b16a2

test:
  secret_key_base: 4a12427373b1ee5b82ca9dfe03a07af71a5b0c8ecbc69e4a201c2fadd36e2a373fb00b8bdba2d842def518867d5373917a7c98c3f5297a439642a101223a4543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
